#:schema node_modules/wrangler/config-schema.json
name = "calendar-extension-backend"
compatibility_date = "2025-01-01"

# Removed nodejs_compat - we now use Web APIs only (fetch, Web Crypto)
# No Node.js-specific dependencies (axios, crypto) anymore

# For Cloudflare Pages deployment with SvelteKit
pages_build_output_dir = ".svelte-kit/cloudflare"

# Environment variables should be added in Cloudflare Pages Dashboard
# Settings > Environment Variables
# Required variables:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY
# - PUBLIC_PADDLE_VENDOR_ID
# - PUBLIC_PADDLE_ENVIRONMENT (sandbox or production)
# - PADDLE_VENDOR_ID
# - PADDLE_VENDOR_AUTH_CODE
# - PADDLE_PUBLIC_KEY
# - PADDLE_WEBHOOK_SECRET
# - JWT_SECRET
# - ADMIN_EMAIL
