#:schema node_modules/wrangler/config-schema.json
name = "calendar-extension-backend2"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages deployment
pages_build_output_dir = ".open-next/assets"

# Environment variables should be added in Cloudflare Pages Dashboard
# Settings > Environment Variables
# Required variables:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
# - SUPABASE_SERVICE_ROLE_KEY
# - PADDLE_VENDOR_ID
# - PADDLE_VENDOR_AUTH_CODE
# - PADDLE_PUBLIC_KEY
# - PADDLE_WEBHOOK_SECRET
# - NEXTAUTH_URL (set after first deployment)
# - NEXTAUTH_SECRET
# - JWT_SECRET
# - ADMIN_EMAIL
# - NODE_ENV=production
